# -*- coding: utf-8 -*-
"""Google_translator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/VarshithaDendukuri/projects-py-/blob/main/Google_translator.ipynb
"""

!pip install googletrans==4.0.0-rc1

#spanish
from googletrans import Translator

def translate_text(text, source_lang, target_lang):
    translator = Translator()
    translation = translator.translate(text, src=source_lang, dest=target_lang)
    return translation.text

if __name__ == "__main__":
    input_text = "hello,i am unhappy,i am sad"  # Fixed the syntax error here
    source_language = "en"
    target_language = "es"
    translated_text = translate_text(input_text, source_language, target_language)
    print(f"Original text: {input_text}")
    print(f"Translated text: {translated_text}")

from googletrans import Translator

def translate_text(text, source_lang, target_lang):
    translator = Translator()
    translation = translator.translate(text, src=source_lang, dest=target_lang)
    return translation.text

if __name__ == "__main__":
    input_text = "hello,i am feeling bored"  # Fixed the syntax error here
    source_language = "en"
    target_language = "hi"
    translated_text = translate_text(input_text, source_language, target_language)
    print(f"Original text: {input_text}")
    print(f"Translated text: {translated_text}")