# -*- coding: utf-8 -*-
"""sketch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/VarshithaDendukuri/projects-py-/blob/main/sketch.ipynb
"""

! pip install opencv-python

import cv2
image = cv2.imread("image.jpg")
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
inverted = 255- gray_image
blur = cv2.GaussianBlur(inverted, (21, 21), 0)
invertedblur = 255-blur
pencil_sketch = cv2.divide(gray_image, invertedblur, scale=256.0)
cv2.imwrite("sketch_image.png", pencil_sketch)
from google.colab.patches import cv2_imshow
cv2_imshow(pencil_sketch)

import cv2

# Load the image
image = cv2.imread("image.jpg")

# Convert to grayscale
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Create pencil sketch effect
inverted = 255 - gray_image
blur = cv2.GaussianBlur(inverted, (21, 21), 0)
invertedblur = 255 - blur
pencil_sketch = cv2.divide(gray_image, invertedblur, scale=256.0)

# Resize to a smaller size (e.g., 300x300 pixels for 1x1 inch at 300 DPI)
small_size = cv2.resize(pencil_sketch, (300, 300))

# Save the smaller sketch
cv2.imwrite("small_sketch.png", small_size)

# Display the image in Google Colab
from google.colab.patches import cv2_imshow
cv2_imshow(small_size)